#Contains all data to be inserted into the database
#All data must be formated as arrays of tuples, to work with sqlite executemany

teams = [
			("ANA", "ANAHEIM DUCKS"),
			("BOS", "BOSTON BRUINS"),
			("BUF", "BUFFALO SABRES"),
			("CGY", "CALGARY FLAMES"),
			("CAR", "CAROLINA HURRICANES"),
			("CHI", "CHICAGO BLACKHAWKS"),
			("COL", "COLORADO AVALANCHE"),
			("CBJ", "COLUMBUS BLUE JACKETS"),
			("DAL", "DALLAS STARS"),
			("DET", "DETROIT RED WINGS"),
			("EDM", "EDMONTON OILERS"),
			("FLA", "FLORIDA PANTHERS"),
			("LAK", "LOS ANGELES KINGS"),
			("MIN", "MINNESOTA WILD"),
			("MTL", "MONTREAL CANADIENS"),
			("NSH", "NASHVILLE PREDATORS"),
			("NJD", "NEW JERSEY DEVILS"),
			("NYI", "NEW YORK ISLANDERS"),
			("NYR", "NEW YORK RANGERS"),
			("OTT", "OTTAWA SENATORS"),
			("PHI", "PHILADELPHIA FLYERS"),
			("PHX", "PHOENIX COYOTES"),
			("PIT", "PITTSBURGH PENGUINS"),
			("SJS", "SAN JOSE SHARKS"),
			("STL", "ST. LOUIS BLUES"),
			("TBL", "TAMPA BAY LIGHTNING"),
			("TOR", "TORONTO MAPLE LEAFS"),
			("VAN", "VANCOUVER CANUCKS"),
			("WSH", "WASHINGTON CAPITALS"),
			("WPG", "WINNIPEG JETS")
		]
		
team_ids = {"ANA" : 1,
			"BOS" : 2,
			"BUF" : 3, 
			"CGY" : 4,
			"CAR" : 5,
			"CHI" : 6,
			"COL" : 7,
			"CBJ" : 8,
			"DAL" : 9,
			"DET" : 10,
			"EDM" : 11,
			"FLA" : 12,
			"LAK" : 13,
			"MIN" : 14,
			"MTL" : 15,
			"NSH" : 16,
			"NJD" : 17,
			"NYI" : 18,
			"NYR" : 19,
			"OTT" : 20,
			"PHI" : 21,
			"PHX" : 22,
			"PIT" : 23,
			"SJS" : 24,
			"STL" : 25,
			"TBL" : 26,
			"TOR" : 27,
			"VAN" : 28,
			"WSH" : 29,
			"WPG" : 30
		}
		
miss_types 	= [
				("Crossbar",), 
				("Over",), 
				("Post",), 
				("Tip", ),
				("Wide",),
				]
				
penl_types = [
				("Boarding",),
				("Broken stick",),
				("Charging",),
				("Clipping",),
				("Closing hand on the puck",),
				("Cross-checking",),
				("Delay of game",),
				("Elbowing",),
				("Goalkeeper interference",),
				("High-sticking",),
				("Holding",),
				("Holding the stick",),
				("Hooking",),
				("Illegal equipment",),
				("Illegal stick",),
				("Instigator",),
				("Interference",),
				("Kneeing",),
				("Leaving penalty bench too early",),
				("Leaving the crease (goalkeeper)",),
				("Participating in the play beyond the center red line (goalkeeper)",),
				("Roughing",),
				("Slashing",),
				("Throwing puck towards opponent's goal (goalkeeper)",),
				("Throwing stick",),
				("Tripping",),
				("Unsportsmanlike conduct",),
				]

play_types 	= [
				("BLOCK",), 
				("FAC",),
				("GIVE",),
				("GOAL",),
				("GEND",),
				("HIT",),
				("MISS",),
				("PEND",),
				("PENL",),
				("PSTR",),
				("SHOT",),
				("STOP",),
				("TAKE",),
				]

shot_types 	= [
				("Backhand",),
				("Snap",),
				("Slap",),
				("Tip",),
				("Wrap",),
				("Wrist",),
				]

stop_types 	= [
				("Frozen",),
				("Goalie",),
				("Icing",),
				("Hand Pass",),
				("High Stick",), 
				("Injury",),
				("In Benches",), 
				("In Crowd",),
				("In Netting",), 
				("Net Off",),
				("TV Timeout",),
				]
				
zone_types 	= [
				("Offensive",), 
				("Neutral",),
				("Defensive",),
				]